###
GET localhost:3000/users

###
GET localhost:3000/users/5

###
POST localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@email.com",
  "password": "gLORRIAVIOS#_2"
}


###
PATCH localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@email.com"
}

########################################
# Post Requests
########################################
###
GET localhost:3000/posts

####
GET localhost:3000/posts/1



###
POST localhost:3000/posts
Content-Type: application/json

{
    "title": "What is new in NestJs",
    "postType": "post",
    "content": "Post Content, and this cool int e h processsss",
    "slug": "what-is-new-in-nestjs",
    "status": "draft",
    "publishedOn": "2023-10-01T00:00:00.000Z",
    "schema": "{\"version\":1,\"blocks\":[{\"type\":\"header\",\"data\":{\"text\":\"Article Header\",\"level\":1}},{\"type\":\"paragraph\",\"data\":{\"text\":\"Article content paragraph\"}}]}",
    "tags": [
        "nestjs",
        "typescript"
    ],
    "metaOptions": [
        {
            "key": "sideBarEnabled",
            "value": true
        }
    ]
}



