####################################
#### Post Requests
####################################

### Get All Posts
GET http://localhost:3000/posts?limit=2&page=2

### Get All Posts of a User
GET http://localhost:3000/posts/users/4?limit=2&page=1

### Get A Post
GET http://localhost:3000/posts/16
Authorization: Bearer {{accessToken}}


### Create A Post
POST localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Common Array methods in Javascript",
  "postType": "series",
  "content": "Enim rationale sit dignissim!Pturient duis tristique, exercitation officia? Donec excepteur, exercitationem vulputate facilis dicta, nisl fuga arcu tempor ante quos egestas maiores magni harum! Nam corrupti! Ridiculus architecto voluptatibus dictumst etiam ligula, augue fusce eligendi maiores perspiciatis dictum! Nulla posuere, anim massa saepe odit? Litora risus dictum.",
  "slug": "common-array-methods-in-javascript1199",
  "status": "draft",
  "schema": "{\"version\":1,\"blocks\":[{\"type\":\"header\",\"data\":{\"text\":\"Article Header\",\"level\":1}},{\"type\":\"paragraph\",\"data\":{\"text\":\"Article content paragraph\"}}]}",
  "featuredImageUrl": "https://google.com/images/testimage.png",
  "tags": [7,9],
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
  }
}

### Update A Post
PATCH localhost:3000/posts
Content-Type: application/json

{
  "id": 13,
  "tags": [
    7,
    8
  ],
  "status": "draft",
  "postType": "post"
}

### Delete A Post
DELETE http://localhost:3000/posts/15